name: "bundle and publish xcall cli to NPM"

on: 
  push:
    branches: 
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          always-auth: false
      - name: publish
        run: npm publish --access public
        env:
          NODE_TOKEN: ${{secrets.NPM_AUTH}}